---
title: "Pvivax2-PSMC"
output: html_document
---
```{r PSMC_Pvivax711712}

library(plyr)
library(ggplot2)

N0=(4*2.0E-9)

Pvivax711712RS <- read.delim("711-712.RS.n20.out", header=F) # cat $combined_trunc_file | grep "RS"
Pvivax711712TR<-read.delim("711-712.TR.n20.out", header=F) # cat $combined_trunc_file | grep "TR"
bootstrp<-rep(1:100,each=26)
rep<-rep(1:26,100)
Pvivax711712TR.theta<-rep(Pvivax711712TR$V2,each=26)
Pvivax711712psmc<-data.frame(rep,bootstrp,(Pvivax711712TR.theta*Pvivax711712RS$V3)/50, (Pvivax711712TR.theta*Pvivax711712RS$V4)/50,2*(((Pvivax711712TR.theta*Pvivax711712RS$V3)/50)/N0),(((Pvivax711712TR.theta*Pvivax711712RS$V4)/50)/N0))
colnames(Pvivax711712psmc)=c("rep","boot","div","theta","time","Ne")
mean_div711712=ddply(Pvivax711712psmc,"rep",summarise,div=mean(div))
mean_theta711712=ddply(Pvivax711712psmc,"rep",summarise,theta=mean(theta))
mean_time711712=ddply(Pvivax711712psmc,"rep",summarise,time=mean(time))
mean_Ne711712=ddply(Pvivax711712psmc,"rep",summarise,Ne=mean(Ne))
Pvivax711712psmc_mean=data.frame(boot=rep(100,26),div=mean_div711712$div,theta=mean_theta711712$theta,time=mean_time711712$time,Ne=mean_Ne711712$Ne)

#unscaled
ggplot(Pvivax711712psmc,aes(x=div,y=theta,group=as.factor(boot)))+geom_line(color="red")+geom_line(data=Pvivax711712psmc_mean,aes(x=div,y=theta))+xlab("divergence Log10")+ylab(expression(theta))+scale_x_log10()+scale_y_log10()

#scaled
ggplot(Pvivax711712psmc,aes(x=time,y=Ne,group=as.factor(boot)))+geom_line(color="red")+geom_line(data=Pvivax711712psmc_mean,aes(x=time,y=Ne))+annotation_logticks() + xlab("log10 Generations")+ylab(expression(paste("log10 ",N[e])))+scale_y_log10()+scale_x_log10()
```

```{r PSMC_Pvivax713714}

library(plyr)
library(ggplot2)

N0=(4*2.0E-9)

Pvivax713714RS <- read.delim("713-714.RS.n20.out", header=F) # cat $combined_trunc_file | grep "RS"
Pvivax713714TR<-read.delim("713-714.TR.n20.out", header=F) # cat $combined_trunc_file | grep "TR"
bootstrp<-rep(1:100,each=26)
rep<-rep(1:26,100)
Pvivax713714TR.theta<-rep(Pvivax713714TR$V2,each=26)
Pvivax713714psmc<-data.frame(rep,bootstrp,(Pvivax713714TR.theta*Pvivax713714RS$V3)/50, (Pvivax713714TR.theta*Pvivax713714RS$V4)/50,2*(((Pvivax713714TR.theta*Pvivax713714RS$V3)/50)/N0),(((Pvivax713714TR.theta*Pvivax713714RS$V4)/50)/N0))
colnames(Pvivax713714psmc)=c("rep","boot","div","theta","time","Ne")
mean_div713714=ddply(Pvivax713714psmc,"rep",summarise,div=mean(div))
mean_theta713714=ddply(Pvivax713714psmc,"rep",summarise,theta=mean(theta))
mean_time713714=ddply(Pvivax713714psmc,"rep",summarise,time=mean(time))
mean_Ne713714=ddply(Pvivax713714psmc,"rep",summarise,Ne=mean(Ne))
Pvivax713714psmc_mean=data.frame(boot=rep(100,26),div=mean_div713714$div,theta=mean_theta713714$theta,time=mean_time713714$time,Ne=mean_Ne713714$Ne)

#unscaled
ggplot(Pvivax713714psmc,aes(x=div,y=theta,group=as.factor(boot)))+geom_line(color="red")+geom_line(data=Pvivax713714psmc_mean,aes(x=div,y=theta))+xlab("divergence Log10")+ylab(expression(theta))+scale_x_log10()+scale_y_log10()

#scaled
ggplot(Pvivax713714psmc,aes(x=time,y=Ne,group=as.factor(boot)))+geom_line(color="red")+geom_line(data=Pvivax713714psmc_mean,aes(x=time,y=Ne))+annotation_logticks() + xlab("log10 Generations")+ylab(expression(paste("log10 ",N[e])))+scale_y_log10()+scale_x_log10()
```


```{r PSMC_PLOT}
##Plots all of them w/ mean and in gens

library(plyr)
library(ggplot2)
theme_set( theme_bw( base_size=18, base_family= "Tw Cen MT"))
scale_colour_manual(values=cbPalette)

#    gray,    orange,   sky blue, blue green, yellow,    blue,      vermillion reddish-purple 
#"#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7"

#unscaled
ggplot(subset(Pvivax713714psmc,div>0),aes(x=div,y=theta,group=as.factor(boot)))+geom_line(color="#009E73")+geom_line(data=subset(Pvivax711712psmc,div>0),color="#56B4E9",aes(x=div,y=theta,group=as.factor(boot)))+annotation_logticks() + xlab("divergence Log10")+ylab(expression(theta))+scale_y_log10()+scale_x_log10()+geom_line(data=subset(Pvivax713714psmc_mean,div>0),aes(x=div,y=theta))+geom_line(data=subset(Pvivax711712psmc_mean,div>0),aes(x=div,y=theta))

#geom_line(data=subset(WbPNG17Dpsmc,div>0),color="#0072B2",aes(x=div,y=theta,group=as.factor(boot)))+geom_line(data=subset(WbPNG48Bpsmc_mean,div>0),aes(x=div,y=theta))+geom_line(data=subset(WbPNG48Bpsmc,div>0),color="#CC79A7",aes(x=div,y=theta,group=as.factor(boot)))+geom_line(data=subset(WbPNG17Dpsmc_mean,div>0),aes(x=div,y=theta))+geom_line(data=subset(WbPNG17Apsmc_mean,div>0),aes(x=div,y=theta))+geom_line(data=subset(WbPNG17Apsmc,div>0),color="#56B4E9",aes(x=div,y=theta,group=as.factor(boot)))

#scaled
ggplot(subset(Pvivax713714psmc,time>0),aes(x=time,y=Ne,group=as.factor(boot)))+geom_line(color="#009E73")+geom_line(data=subset(Pvivax711712psmc,time>0),color="#56B4E9",aes(x=time,y=Ne,group=as.factor(boot)))+xlab("log10 Generations")+ylab(expression(paste("log10 ",N[e])))+geom_line(data=subset(Pvivax713714psmc_mean,time>0),aes(x=time,y=Ne))+geom_line(data=subset(Pvivax711712psmc_mean,time>0),aes(x=time,y=Ne))+scale_y_log10()+scale_x_log10(breaks=c(100,1000,10000,100000,500000))+annotation_logticks()

#geom_line(data=subset(WbPNG17Dpsmc,time>0),color="#0072B2",aes(x=time,y=Ne,group=as.factor(boot)))+geom_line(data=subset(WbPNG48Bpsmc_mean,time>0),aes(x=time,y=Ne))+geom_line(data=subset(WbPNG48Bpsmc,time>0),color="#CC79A7",aes(x=time,y=Ne,group=as.factor(boot)))+geom_line(data=subset(WbPNG17Dpsmc_mean,time>0),aes(x=time,y=Ne))+geom_line(data=subset(WbPNG17Apsmc_mean,time>0),aes(x=time,y=Ne))+geom_line(data=subset(WbPNG17Apsmc,time>0),color="#56B4E9",aes(x=time,y=Ne,group=as.factor(boot)))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
```

```{r MSMC_PLOT}
library(plyr)
library(ggplot2)
theme_set( theme_bw( base_size=18, base_family= "Tw Cen MT"))
scale_colour_manual(values=cbPalette)
mu=2.9E-9

WbPNGL3msmcR <- read.delim("~/WbPNGL3-ALL.phased.msmcR.out.final.txt", header=T)
WbPNGL3msmcR$timeL=WbPNGL3msmcR$left_time_boundary/mu
WbPNGL3msmcR$timeR=WbPNGL3msmcR$right_time_boundary/mu
WbPNGL3msmcR$Ne=(1/WbPNGL3msmcR$lambda_00)/(2*mu)

number_ticks <- function(n) {function(limits) pretty(limits, n)}
#+scale_x_continuous(breaks=number_ticks(10))+scale_y_continuous(breaks=number_ticks(10))

#scaled
ggplot(subset(WbPNGL3msmcR, timeR<6000),aes(x=log10(timeR),y=log10(Ne)))+geom_line(color="#CC79A7") + xlab("log10 Generations")+ylab(expression(paste("log10 ",N[e])))+scale_x_continuous(breaks=number_ticks(10))+scale_y_continuous(breaks=number_ticks(10))+annotation_logticks()

#scaled no log
ggplot(subset(WbPNGL3msmcR, timeR<6000),aes(x=timeR,y=Ne))+geom_line(color="#CC79A7") + xlab("Generations")+ylab(expression(paste(N[e])))+scale_x_continuous(breaks=number_ticks(10))+scale_y_continuous(breaks=number_ticks(10))

```